### ISSUE TITLE
Crashes on iOS about 20% of the time.

### ISSUE THREAD

**Issue by btknorr** [appcelerator-modules/titanium-identity#8] opened 2017-12-20 16:00 UTC
There seems to be a stability issue with the module on iOS.  We are testing this for one of Axway's enterprise clients, and about 20% of the time it crashes the entire app after processing a user's Face ID.

We are on the latest everything...AppC 7.0, etc...

Here are some details of the crashes:

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)

Thread 13 Crashed:
0   libobjc.A.dylib               	0x00000001807a81a0 objc_retain + 16
1   Jason's Deli                  	0x0000000102a24568 0x102544000 + 5113192
2   libdispatch.dylib             	0x0000000180ec1088 _dispatch_call_block_and_release + 24
3   libdispatch.dylib             	0x0000000180ec1048 _dispatch_client_callout + 16
4   libdispatch.dylib             	0x0000000180efc4e0 _dispatch_queue_override_invoke$VARIANT$armv81 + 700
5   libdispatch.dylib             	0x0000000180f02418 _dispatch_root_queue_drain + 564
6   libdispatch.dylib             	0x0000000180f02180 _dispatch_worker_thread3 + 112
7   libsystem_pthread.dylib       	0x0000000181167120 _pthread_wqthread + 1268
8   libsystem_pthread.dylib       	0x0000000181166c20 start_wqthread + 4

----------------------------------------------------------------------------

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)

Thread 12 Crashed:
0   JavaScriptCore                	0x0000000187f0cf98 JSC::speculationFromStructure+ 659352 (JSC::Structure*) + 0
1   JavaScriptCore                	0x0000000188114d4c JSC::CodeBlock::updateAllPredictionsAndCountLiveness+ 2788684 (unsigned int&, unsigned int&) + 352
2   JavaScriptCore                	0x0000000188111678 JSC::CodeBlock::UnconditionalFinalizer::finalizeUnconditionally+ 2774648 () + 36
3   JavaScriptCore                	0x00000001883e5d4c JSC::Heap::runEndPhase+ 5741900 (JSC::GCConductor) + 1584
4   JavaScriptCore                	0x00000001883e4368 JSC::Heap::runCurrentPhase+ 5735272 (JSC::GCConductor, JSC::CurrentThreadState*) + 220
5   JavaScriptCore                	0x00000001883e944c JSC::Heap::Thread::work+ 5755980 () + 32
6   JavaScriptCore                	0x0000000188784c38 WTF::Function<void ()>::CallableWrapper<WTF::AutomaticThread::start(WTF::AbstractLocker const&)::$_0>::call+ 9538616 () + 360
7   JavaScriptCore                	0x0000000187e75660 WTF::threadEntryPoint+ 38496 (void*) + 120
8   JavaScriptCore                	0x0000000187e755a0 WTF::wtfThreadEntryPoint+ 38304 (void*) + 84
9   libsystem_pthread.dylib       	0x000000018116831c _pthread_body + 308
10  libsystem_pthread.dylib       	0x00000001811681e8 _pthread_body + 0
11  libsystem_pthread.dylib       	0x0000000181166c28 thread_start + 4

**Comment by btknorr** [comment] 2017-12-27 19:07
We have a workaround or maybe it's just a best practice implementation that resolves these crashes on iOS.  Basically you can't create a new keychain item for each use, instead you have to create a singleton and only handle "one-time" event listeners accordingly.  On android it works fine either way.

**Comment by hansemannn** [comment] 2017-12-27 20:39
Thanks @btknorr, we did not forget you! But I am on vacation until next week (since last week), so we'll provide a patch next week. Maybe @vijaysingh-axway can take a look in the mean time? Probably it's just a retain cycle / bad address error causing this issue. Sorry for the inconvenience caused by this!

**Comment by vijaysingh-axway** [comment] 2017-12-28 04:13
I'll look in this. Thanks!

**Comment by hansemannn** [comment] 2018-01-29 10:13
Closing in favor of the [JIRA ticket](https://jira.appcelerator.org/browse/MOD-2396) (cc @vijaysingh-axway)

**Closed by hansemannn** 2018-01-29 10:13 UTC
